# Generated by Django 6.0.3 on 2026-04-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_about_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='About_description',
            new_name='about_description',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='About_heading',
            new_name='about_heading',
        ),
    ]
